"""empty message

Revision ID: 3a72493857b1
Revises: 
Create Date: 2025-05-07 18:18:14.529974

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a72493857b1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fitness_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.String(length=50), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('total_time_seconds', sa.Integer(), nullable=True),
    sa.Column('total_distance_km', sa.Float(), nullable=True),
    sa.Column('total_calories_kcal', sa.Float(), nullable=True),
    sa.Column('average_speed_kmh', sa.Float(), nullable=True),
    sa.Column('average_rpm', sa.Float(), nullable=True),
    sa.Column('average_mets', sa.Float(), nullable=True),
    sa.Column('raw_data', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('data_points',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('speed_kmh', sa.Float(), nullable=True),
    sa.Column('rpm', sa.Float(), nullable=True),
    sa.Column('distance_km', sa.Float(), nullable=True),
    sa.Column('calories_kcal', sa.Float(), nullable=True),
    sa.Column('time_seconds', sa.Integer(), nullable=True),
    sa.Column('mets', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['fitness_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('data_points')
    op.drop_table('fitness_sessions')
    # ### end Alembic commands ###
